# Site settings
title: 郝鑫的博客
email: arieshx.v@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  郝鑫的博客
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://haoxin.org # the base hostname & protocol for your site
rss_url: /pages/feed.xml
author: Hao Xin

# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'
recent_num: 20

# Social account
#twitter: 
#weibo: suyan0830
github: arieshx
#instagram: suyan404
#linkedin: suyan404

# avatar and Favicon
avatar: ./img/liufeier.png
favicon: ./img/haoxin.jpg


# disqus config
#disqus:
#  shortname: suyan-zh

# google analytics config
#ga:
#  id: UA-54767140-1
#  url: yansu.org

# Build settings
permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge
mathjax: disabled
sass:
  style: compressed

# Jekyll Plugin
# https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

